""" version which can be consumed from within the module """
VERSION_STR = "0.0.9"
DESCRIPTION = "pyfakeuse helps you fool development environments and code inspectors"
APP_NAME = "pyfakeuse"
LOGGER_NAME = "pyfakeuse"
